# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."terminus-database" = {
    image = "postgres:18.3-alpine";
    environment = {
      "POSTGRES_DB" = "terminus_production";
      "POSTGRES_PASSWORD" = "supersecret";
      "POSTGRES_USER" = "terminus";
    };
    volumes = [
      "terminus_database-data:/var/lib/postgresql:rw"
    ];
    ports = [
      "5432:5432/tcp"
    ];
    cmd = [ "-p" "5432" ];
    log-driver = "journald";
    extraOptions = [
      "--cpus=1"
      "--health-cmd=pg_isready --username terminus --dbname terminus_production --port 5432"
      "--health-interval=10s"
      "--health-retries=3"
      "--health-timeout=5s"
      "--memory=2147483648b"
      "--network-alias=database"
      "--network=terminus_default"
    ];
  };
  systemd.services."docker-terminus-database" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-terminus_default.service"
      "docker-volume-terminus_database-data.service"
    ];
    requires = [
      "docker-network-terminus_default.service"
      "docker-volume-terminus_database-data.service"
    ];
    partOf = [
      "docker-compose-terminus-root.target"
    ];
    wantedBy = [
      "docker-compose-terminus-root.target"
    ];
  };
  virtualisation.oci-containers.containers."terminus-init-certificates" = {
    image = "ghcr.io/usetrmnl/terminus:latest";
    environment = {
      "CERTIFICATE_URLS" = "";
    };
    volumes = [
      "terminus_certificates:/etc/ssl/certs:rw"
    ];
    cmd = [ "scripts/docker/install-certificates" ];
    user = "root";
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"/bin/bash\", \"-c\"]"
      "--network-alias=init-certificates"
      "--network=terminus_default"
    ];
  };
  systemd.services."docker-terminus-init-certificates" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-terminus_default.service"
      "docker-volume-terminus_certificates.service"
    ];
    requires = [
      "docker-network-terminus_default.service"
      "docker-volume-terminus_certificates.service"
    ];
    partOf = [
      "docker-compose-terminus-root.target"
    ];
    wantedBy = [
      "docker-compose-terminus-root.target"
    ];
  };
  virtualisation.oci-containers.containers."terminus-keyvalue" = {
    image = "valkey/valkey:9-alpine";
    volumes = [
      "terminus_keyvalue-data:/data:rw"
    ];
    ports = [
      "6379:6379/tcp"
    ];
    cmd = [ "valkey-server" "--requirepass" "redis_secret" "--maxmemory" "512mb" "--maxmemory-policy" "noeviction" "--port" "6379" ];
    log-driver = "journald";
    extraOptions = [
      "--cpus=0.5"
      "--health-cmd=redis-cli -p 6379 ping || exit 1"
      "--health-interval=10s"
      "--health-retries=3"
      "--health-start-period=2s"
      "--health-timeout=5s"
      "--memory=536870912b"
      "--network-alias=keyvalue"
      "--network=terminus_default"
    ];
  };
  systemd.services."docker-terminus-keyvalue" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-terminus_default.service"
      "docker-volume-terminus_keyvalue-data.service"
    ];
    requires = [
      "docker-network-terminus_default.service"
      "docker-volume-terminus_keyvalue-data.service"
    ];
    partOf = [
      "docker-compose-terminus-root.target"
    ];
    wantedBy = [
      "docker-compose-terminus-root.target"
    ];
  };
  virtualisation.oci-containers.containers."terminus-web" = {
    image = "ghcr.io/usetrmnl/terminus:latest";
    environment = {
      "API_URI" = "http://192.168.1.11:2300";
      "APP_SECRET" = "4675543666d62524d775150587a324b3337774c53443372674e5033703058444a4969376175647563574d6e4b47636e614666353935393566675038676239326e";
      "APP_SETUP" = "true";
      "DATABASE_URL" = "postgres://terminus:supersecret@database:5432/terminus_production";
      "HANAMI_PORT" = "2300";
      "KEYVALUE_URL" = "redis://:redis_secret@keyvalue:6379/0";
    };
    volumes = [
      "terminus_certificates:/etc/ssl/certs:rw"
      "terminus_web-uploads:/app/public/uploads:rw"
    ];
    ports = [
      "2300:2300/tcp"
    ];
    dependsOn = [
      "terminus-database"
      "terminus-init-certificates"
      "terminus-keyvalue"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cpus=1"
      "--health-cmd=curl --fail --silent http://localhost:2300/up"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=45s"
      "--health-timeout=10s"
      "--init=true"
      "--memory=1073741824b"
      "--network-alias=web"
      "--network=terminus_default"
    ];
  };
  systemd.services."docker-terminus-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-terminus_default.service"
      "docker-volume-terminus_certificates.service"
      "docker-volume-terminus_web-uploads.service"
    ];
    requires = [
      "docker-network-terminus_default.service"
      "docker-volume-terminus_certificates.service"
      "docker-volume-terminus_web-uploads.service"
    ];
    partOf = [
      "docker-compose-terminus-root.target"
    ];
    wantedBy = [
      "docker-compose-terminus-root.target"
    ];
  };
  virtualisation.oci-containers.containers."terminus-worker" = {
    image = "ghcr.io/usetrmnl/terminus:latest";
    environment = {
      "API_URI" = "http://192.168.1.11:2300";
      "APP_SECRET" = "4675543666d62524d775150587a324b3337774c53443372674e5033703058444a4969376175647563574d6e4b47636e614666353935393566675038676239326e";
      "DATABASE_URL" = "postgres://terminus:supersecret@database:5432/terminus_production";
      "HANAMI_PORT" = "2300";
      "KEYVALUE_URL" = "redis://:redis_secret@keyvalue:6379/0";
    };
    volumes = [
      "terminus_certificates:/etc/ssl/certs:rw"
      "terminus_web-uploads:/app/public/uploads:rw"
    ];
    cmd = [ "bundle" "exec" "sidekiq" "-r" "./config/sidekiq.rb" ];
    dependsOn = [
      "terminus-web"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cpus=1"
      "--health-cmd=[\"pgrep\", \"-f\", \"sidekiq\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=45s"
      "--health-timeout=10s"
      "--init=true"
      "--memory=1073741824b"
      "--network-alias=worker"
      "--network=terminus_default"
    ];
  };
  systemd.services."docker-terminus-worker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-terminus_default.service"
      "docker-volume-terminus_certificates.service"
      "docker-volume-terminus_web-uploads.service"
    ];
    requires = [
      "docker-network-terminus_default.service"
      "docker-volume-terminus_certificates.service"
      "docker-volume-terminus_web-uploads.service"
    ];
    partOf = [
      "docker-compose-terminus-root.target"
    ];
    wantedBy = [
      "docker-compose-terminus-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-terminus_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f terminus_default";
    };
    script = ''
      docker network inspect terminus_default || docker network create terminus_default
    '';
    partOf = [ "docker-compose-terminus-root.target" ];
    wantedBy = [ "docker-compose-terminus-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-terminus_certificates" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect terminus_certificates || docker volume create terminus_certificates
    '';
    partOf = [ "docker-compose-terminus-root.target" ];
    wantedBy = [ "docker-compose-terminus-root.target" ];
  };
  systemd.services."docker-volume-terminus_database-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect terminus_database-data || docker volume create terminus_database-data
    '';
    partOf = [ "docker-compose-terminus-root.target" ];
    wantedBy = [ "docker-compose-terminus-root.target" ];
  };
  systemd.services."docker-volume-terminus_keyvalue-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect terminus_keyvalue-data || docker volume create terminus_keyvalue-data
    '';
    partOf = [ "docker-compose-terminus-root.target" ];
    wantedBy = [ "docker-compose-terminus-root.target" ];
  };
  systemd.services."docker-volume-terminus_web-uploads" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect terminus_web-uploads || docker volume create terminus_web-uploads
    '';
    partOf = [ "docker-compose-terminus-root.target" ];
    wantedBy = [ "docker-compose-terminus-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-terminus-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
